version: "3.3"

services:
  pgdb:
    image: library/postgres:13.2
    deploy:
      placement:
        constraints:
          - "node.labels.nodeIdentity==master"
      mode: global
    networks:
      - backend
    hostname: analysis-pgdb
    volumes:
      - /etc/analysis/analysis-db/create.sql:/docker-entrypoint-initdb.d/01_create.sql
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: harb
      POSTGRES_PASSWORD: HueHue123
      POSTGRES_DB: analysis

  mongodb:
    image: mongo:latest
    hostname: analysis-mongodb
    deploy:
      placement:
        constraints:
          - "node.labels.nodeIdentity==master"
      mode: global
    networks:
      - backend
    volumes:
      - mongodb-storage:/data/db
      - mongodb-log:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  api:
    image: xburrow/analysis-api:latest-prod
    networks:
      - backend
      - frontend
      - proxy-web_proxy-bridge
    depends_on:
      - pgdb
      - mongodb
    hostname: analysis-api
    deploy:
      placement:
        constraints:
          - "node.labels.nodeIdentity==worker"
      replicas: 5
    ports:
      - 7070
    environment:
      SARUMAN_API_KEY: ${SARUMAN_API_KEY}
      SARUMAN_URL: ${API_SARUMAN_URL}

  jobs:
    image: xburrow/analysis-jobs:latest-prod
    hostname: analysis-jobs
    deploy:
      placement:
        constraints:
          - "node.labels.nodeIdentity==master"
        mode: global
    environment:
      SARUMAN_API_KEY: ${SARUMAN_API_KEY}
      SARUMAN_URL: ${JOBS_SARUMAN_URL}

  web:
    image: xburrow/analysis-web:latest-prod
    networks:
      - frontend
      - proxy-web_proxy-bridge
    depends_on:
      - api
    hostname: analysis-web
    deploy:
      placement:
        constraints:
          - "node.labels.nodeIdentity==master"
      replicas: 5
    ports:
      - 80

volumes:
  db-storage:
  mongodb-storage:
  mongodb-log:

networks:
  backend:
  frontend:
  proxy-web_proxy-bridge:
    external: true