version: "3.3"

services:
  db:
    image: library/postgres:13.2
    networks:
      - backend
    restart: always
    hostname: analysis-db
    volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/01_create.sql
      - analysis-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: harb
      POSTGRES_PASSWORD: HueHue123
      POSTGRES_DB: analysis

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 7071:8080
    hostname: analysis-adminer

  api:
    image: xburrow/analysis-api:latest-prod
    networks:
      - backend
      - frontend
    volumes:
    - /docker-mnt/analysis-api/certs:/certs
    depends_on:
      - db
    hostname: analysis-api
    deploy:
      replicas: 5
    ports:
      - target: 7070
        mode: ingress
    environment:
      SARUMAN_API_KEY: 270492bf-bbfd-4974-a61b-507aa948e99d
      SARUMAN_URL: https://saruman-api.glamav.systems/api/v1/config/analysis-api-prod/


volumes:
 analysis-storage:

networks:
  backend:
  frontend: